### ISSUE TITLE
sanitize_key not recognized as an 'escaping function'

### ISSUE THREAD

**Issue by krisgale-zz** [10up/phpcs-composer#8]
i'd expect that `<?php echo sanitize_key( $string ); ?>` would be allowed.

**Comment by peterwilsoncc** [comment]
This was fixed upstream in WPCS 2.2.0, as the composer.lock file includes WPCS 2.3.0 this can be closed as fixed upstream. See https://github.com/WordPress/WordPress-Coding-Standards/pull/1786

As there isn't a fixed upstream label, I'll close this as wontfix as this issue was valid at the time it was reported.
